swagger: '2.0'
info:
  version: '1.0'
  title: Nombre de tu API
paths:
  /api/productos:
    get:
      summary: Obtener lista de productos
      responses:
        200:
          description: Lista de productos
          schema:
            type: array
            items:
              $ref: '#/definitions/Producto'
    post:
      summary: Crear un nuevo producto
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/NuevoProducto'
      responses:
        201:
          description: Producto creado exitosamente
definitions:
  Producto:
    type: object
    properties:
      id:
        type: integer
      nombre:
        type: string
      # Otros atributos del producto
  NuevoProducto:
    type: object
    properties:
      nombre:
        type: string
      # Otros atributos del nuevo producto